name: shoppingmall
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  provider: ^6.0.5
  geolocator: ^10.0.1
  permission_handler: ^10.4.5
  google_maps_flutter: ^2.5.0
  geocoder_buddy: ^1.0.1
  shared_preferences: ^2.2.1
  carousel_slider: ^4.2.1
  flutter_slider_drawer: ^2.0.0
  flutter_slider_drawer_v: ^2.0.2
  image_picker: ^1.0.4
  email_validator: ^2.1.17
  location: ^5.0.0
  firebase_storage: ^11.2.6
  flutter_easyloading: ^3.0.5
  flutterflow_paginate_firestore: ^1.0.3+1
  persistent_bottom_nav_bar: ^5.0.2
  url_launcher: ^6.1.14
  expandable_text: 2.3.0
  dotted_border: ^2.1.0
  date_time_format: ^2.0.1
  intl: ^0.18.1
  search_page: ^2.3.0
  pdf: ^3.10.4
  path_provider: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

